datasources:
  -  access: 'proxy'                       # make grafana perform the requests
     type: vertamedia-clickhouse-datasource
     editable: true                        # whether it should be editable
     is_default: true                      # whether this should be the default DS
     name: 'ClickHouse'                    # name of the datasource
     org_id: 1                             # id of the organization to tie this datasource to
     url: 'http://clickhouse:8123'         # url of the prom instance
     version: 1                            # well, versioning